import React, { useState, useEffect } from 'react';
import { EXPIRATION_OPTIONS, MOCK_HTML_TEMPLATE } from '../constants';
import { AIAssistant } from './AIAssistant';
import { Button } from './Button';
import { supabase } from '../services/supabaseClient';

interface CreatorDashboardProps {
  editingId?: string | null;
}

export const CreatorDashboard: React.FC<CreatorDashboardProps> = ({ editingId }) => {
  const [clientName, setClientName] = useState('');
  const [password, setPassword] = useState('');
  const [expiration, setExpiration] = useState(EXPIRATION_OPTIONS[0].value);
  const [htmlContent, setHtmlContent] = useState(MOCK_HTML_TEMPLATE);
  const [generatedLink, setGeneratedLink] = useState<string | null>(null);
  const [showAI, setShowAI] = useState(true);
  const [showPreview, setShowPreview] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isLoadingData, setIsLoadingData] = useState(false);

  // Load data if editing
  useEffect(() => {
    if (editingId) {
      const loadPortal = async () => {
        setIsLoadingData(true);
        const { data, error } = await supabase
          .from('portals')
          .select('*')
          .eq('id', editingId)
          .single();

        if (data && !error) {
          setClientName(data.client_name);
          setPassword(data.password);
          setHtmlContent(data.html_content);
          // Calculate remaining time essentially by checking diff, 
          // but for simplicity in UI, we default selection to 1 Day or keep logic simple.
          // Ideally, we might want to let them ADD time, but here we just reset logic or keep current.
          // For now, we won't override the dropdown default unless we want to do complex math.
        }
        setIsLoadingData(false);
      };
      loadPortal();
    }
  }, [editingId]);

  const handleSave = async () => {
    if (!clientName || !password) {
      alert("Please fill in Client Name and Password.");
      return;
    }

    setIsSaving(true);

    try {
      const payload = {
        client_name: clientName,
        html_content: htmlContent,
        password: password,
        // If editing, we update the expiration relative to NOW, essentially extending or resetting it
        expires_at: Date.now() + expiration, 
      };

      let result;

      if (editingId) {
        // Update existing
        result = await supabase
          .from('portals')
          .update(payload)
          .eq('id', editingId)
          .select('id')
          .single();
      } else {
        // Create new
        result = await supabase
          .from('portals')
          .insert(payload)
          .select('id')
          .single();
      }

      const { data, error } = result;

      if (error) {
        throw error;
      }

      if (data) {
        // Construct the link using the current origin
        const origin = window.location.origin + window.location.pathname;
        const cleanOrigin = origin.endsWith('/') ? origin.slice(0, -1) : origin;
        const link = `${cleanOrigin}/#portal/${data.id}`;
        setGeneratedLink(link);
      }
    } catch (e: any) {
      console.error(e);
      alert(`Error saving portal: ${e.message || 'Unknown error'}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleInsertCode = (code: string) => {
    if (code.includes('<!DOCTYPE html>') || code.includes('<html')) {
        setHtmlContent(code);
    } else {
        if (htmlContent.includes('</body>')) {
            setHtmlContent(htmlContent.replace('</body>', `${code}\n</body>`));
        } else {
            setHtmlContent(prev => prev + '\n' + code);
        }
    }
  };

  const handleInsertImage = (url: string) => {
      const imgTag = `<img src="${url}" alt="Generated by Gemini" style="max-width: 100%; height: auto; border-radius: 8px; margin: 10px 0;" />`;
      if (htmlContent.includes('</body>')) {
        setHtmlContent(htmlContent.replace('</body>', `${imgTag}\n</body>`));
    } else {
        setHtmlContent(prev => prev + '\n' + imgTag);
    }
  };

  const goBack = () => {
    window.location.hash = '';
  };

  const isLocalhost = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';

  if (isLoadingData) {
    return (
      <div className="flex h-screen items-center justify-center bg-slate-950 text-white">
        Loading portal data...
      </div>
    );
  }

  return (
    <div className="flex h-screen bg-slate-950 text-slate-100 overflow-hidden">
      {/* Main Content */}
      <div className="flex-1 flex flex-col h-full overflow-hidden">
        {/* Header */}
        <header className="h-16 border-b border-slate-800 bg-slate-900 flex items-center justify-between px-6">
          <div className="flex items-center gap-4">
             <Button variant="ghost" onClick={goBack} className="!p-2">
                ← Back
             </Button>
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-gradient-to-tr from-blue-500 to-purple-600 rounded-lg flex items-center justify-center font-bold text-white">S</div>
              <h1 className="font-semibold text-lg tracking-tight">
                SecurePage <span className="text-slate-500 font-normal">{editingId ? 'Editor' : 'Creator'}</span>
              </h1>
            </div>
          </div>
          <div className="flex items-center gap-3">
             <button onClick={() => setShowAI(!showAI)} className={`px-3 py-1.5 rounded text-sm font-medium border ${showAI ? 'bg-blue-600 border-blue-600 text-white' : 'border-slate-600 text-slate-300'}`}>
                {showAI ? 'Hide AI Assistant' : 'Show AI Assistant'}
             </button>
             <Button onClick={() => setShowPreview(true)} variant="secondary">
                Preview
             </Button>
             <Button onClick={handleSave} variant="primary" isLoading={isSaving}>
               {isSaving ? 'Saving...' : (editingId ? 'Update Portal' : 'Generate Secure Link')}
             </Button>
          </div>
        </header>

        <div className="flex-1 flex overflow-hidden">
            {/* Form & Editor */}
            <div className="flex-1 flex flex-col p-6 overflow-y-auto">
                
                {/* Configuration Panel */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6 p-6 bg-slate-900 rounded-xl border border-slate-800">
                    <div>
                        <label className="block text-sm font-medium text-slate-400 mb-1">Client Name</label>
                        <input 
                            type="text" 
                            className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                            placeholder="e.g. Acme Corp"
                            value={clientName}
                            onChange={e => setClientName(e.target.value)}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-400 mb-1">Access Password</label>
                        <input 
                            type="text" 
                            className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                            placeholder="Secret123"
                            value={password}
                            onChange={e => setPassword(e.target.value)}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-slate-400 mb-1">
                            {editingId ? 'Extend/Reset Access Duration' : 'Access Duration'}
                        </label>
                        <select 
                            className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white focus:ring-2 focus:ring-blue-500 outline-none"
                            value={expiration}
                            onChange={e => setExpiration(Number(e.target.value))}
                        >
                            {EXPIRATION_OPTIONS.map(opt => (
                                <option key={opt.label} value={opt.value}>{opt.label}</option>
                            ))}
                        </select>
                    </div>
                </div>

                {/* Editor Area */}
                <div className="flex-1 flex flex-col min-h-[400px]">
                    <div className="flex justify-between items-center mb-2">
                        <label className="text-sm font-medium text-slate-400">HTML Source Code</label>
                        <span className="text-xs text-slate-500">Edit directly or use AI to generate</span>
                    </div>
                    <textarea 
                        className="flex-1 bg-slate-900 border border-slate-800 rounded-xl p-4 font-mono text-sm text-slate-300 focus:ring-2 focus:ring-blue-500 outline-none resize-none leading-relaxed"
                        value={htmlContent}
                        onChange={e => setHtmlContent(e.target.value)}
                        spellCheck={false}
                    />
                </div>

                {/* Preview Modal Overlay */}
                {showPreview && (
                    <div className="fixed inset-0 bg-slate-950 z-[100] flex flex-col">
                        <header className="h-16 bg-slate-900 border-b border-slate-800 flex items-center justify-between px-6 shadow-md">
                            <div className="flex items-center gap-2">
                                <span className="text-blue-400">👁️</span>
                                <h2 className="text-white font-semibold">Live Preview</h2>
                            </div>
                            <Button variant="secondary" onClick={() => setShowPreview(false)}>
                                Close Preview
                            </Button>
                        </header>
                        <div className="flex-1 bg-white relative">
                            <iframe 
                                title="Page Preview"
                                srcDoc={htmlContent}
                                className="w-full h-full border-none absolute inset-0"
                                sandbox="allow-scripts allow-popups allow-forms"
                            />
                        </div>
                    </div>
                )}

                {/* Result Modal Overlay */}
                {generatedLink && (
                    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
                        <div className="bg-slate-900 rounded-2xl border border-slate-700 p-8 max-w-2xl w-full shadow-2xl">
                            <h2 className="text-2xl font-bold text-white mb-4">
                                {editingId ? 'Portal Updated Successfully!' : 'Portal Created Successfully!'} 🚀
                            </h2>
                            <p className="text-slate-400 mb-6">
                                Share this link with <strong>{clientName}</strong>. They will need the password: <span className="font-mono bg-slate-800 px-2 py-1 rounded text-blue-400">{password}</span>
                            </p>
                            
                            {isLocalhost && (
                              <div className="bg-yellow-500/10 border border-yellow-500/50 p-3 rounded text-yellow-200 text-sm mb-4 flex gap-2 items-start">
                                <span className="text-xl">⚠️</span>
                                <div>
                                  <strong>Localhost Warning:</strong> You are currently running this app locally. 
                                  External users cannot access the link starting with <code>localhost</code> or <code>127.0.0.1</code>. 
                                  Please deploy this application to a public server (like Vercel or Netlify) to share it.
                                </div>
                              </div>
                            )}

                            <div className="bg-slate-950 p-4 rounded-lg border border-slate-800 mb-6 flex items-center gap-3">
                                <input 
                                    readOnly 
                                    value={generatedLink} 
                                    className="flex-1 bg-transparent border-none text-slate-300 text-sm focus:ring-0 truncate font-mono"
                                />
                                <Button 
                                    variant="secondary" 
                                    onClick={() => {
                                        navigator.clipboard.writeText(generatedLink);
                                        alert("Copied to clipboard!");
                                    }}
                                >
                                    Copy
                                </Button>
                            </div>
                            
                            <div className="flex justify-end">
                                <Button variant="ghost" onClick={() => setGeneratedLink(null)}>Close</Button>
                            </div>
                        </div>
                    </div>
                )}
            </div>

            {/* AI Assistant Sidebar */}
            {showAI && (
                <AIAssistant 
                    onInsertCode={handleInsertCode}
                    onInsertImage={handleInsertImage}
                    currentHTML={htmlContent}
                />
            )}
        </div>
      </div>
    </div>
  );
};